### ISSUE TITLE
critic.socket only added if quickstart is enabled

### ISSUE THREAD

**Issue by Zitrax** [jensl/critic#103]
I got an error trying to rebase using FiddleAndTweak:

> Repository is not configured properly!  Please add
[critic]
socket = \<socket path>
name = \<repository name>
to the repository's configuration file.

_(Sidenote: the error message was not formatted properly in the error dialog)_

And checking it the name setting was there but not socket. Adding it manually to the repo fixed the problem.

Then I noticed [these lines](https://github.com/jensl/critic/blob/8eb0611583911980e5aab4b383f0cedb7488337b/src/operation/addrepository.py#L100:L101) that sets the socket only if `configuration.debug.IS_QUICKSTART` is enabled.

Should that check for `IS_QUICKSTART` really be there ? I don't really know what the quickstart is about - but apparently I am not using it.

**Comment by jensl** [comment]
So, for normal installations, [the installation script](https://github.com/jensl/critic/blob/8eb0611583911980e5aab4b383f0cedb7488337b/installation/git.py#L24) sets the `critic.socket` configuration in Git's system-wide configuration, thus setting a default for all users and repositories that is possible to override both by users and per repository.

This system-wide setting can "get lost" if you have multiple versions of Git installed, since they might use different config files (e.g. `/etc/gitconfig` and `/usr/local/etc/gitconfig`).

**Comment by jensl** [comment]
Oh, and "quickstart" here refers to the `quickstart.py` script in the root directly, which creates a minimal Critic installation in a temporary location that uses Python's `sqlite` and `wsgiref.simple_server` packages and doesn't require root. It's very convenient for quick testing and development of Critic, but is generally not suitable or intended for actual "production" use.

**Comment by Zitrax** [comment]
Aha, thanks. 

And indeed I have installed/built a newer git separately and used that so that seem to be why I saw this problem. I had not used FiddleAndTweak on this install before I added the newer git.

**Comment by Zitrax** [comment]
Closing since it was an issue on my side.
