### ISSUE TITLE
Create a review is no-ending

### ISSUE THREAD

**Issue by fyfcauc** [jensl/critic#92]
Guys, sorry to interrupt you, I encounter an issue: I can create repository and push branch by web page UI, but if I want create a review by push "r/XXX" or from web page UI, the operation is ever-lasting............

And I can not get this instruction well(so I do not conduct this operation): "you must set up the 'critic' system user (or whatever user name was chosen during installation) to have ssh access without the need of a password", what does that mean? Can you give me a easier-explain? :-), sorry my poor english.

looks like this is my issue's cause? Or if there any log I can check?

Thx,  :-)

**Comment by fyfcauc** [comment]
Additional info, the url which is generated to create review is opened ever-lasting and I can not find this url in critic's log: /var/log/critic/main/access.log.   while no error in error.log.

**Comment by jensl** [comment]
The logs to check are /var/log/critic/main/*.log. In this case, access.log and githook.log are the likely candidates, if anything interesting has been logged.

I'm a bit confused what's going on, so asking some questions just to clarify: when creating a review via push, is it the actual "git push" command that never finishes, or does it finish normally, and loading the review front-page never finishes?

If the second, it might simply be that the URL that is output in response to the push is incorrect. It's simply generated from the system configuration in /etc/critic/main/configuration/base.py, for instance the system's hostname and how it's accessed (HTTP or HTTPS). This system configuration is mostly used for constructing URLs. If it's wrong, you'll probably still be able to access the system, but the system will construct incorrect URLs, for instance in response to git pushes and in emails. If that's the case, then just fix the system configuration according to how the system is actually access, and restart using "criticctl restart" (as root).

**Comment by jensl** [comment]
Oh, and that SSH access quote simply means that if you want Critic to fetch branches from repositories on other machines (e.g. when you create a new repository and tell Critic to clone it from somewhere), and the URL of the repository to fetch from is "ssh://hostname/path" or just "hostname:/path", in which case Git will use SSH to access the machine, then the critic system/UNIX user needs to be able to log in on that machine without a password prompt.

If you're not using such a setup, then this is not relevant to you at all.

To test that it works as expected, you can log in as root on the machine running Critic, run "su -l -s $SHELL critic" and then "ssh othermachine". You should be able to log in (or at least not have an authentication failure) without a password prompt.

**Comment by fyfcauc** [comment]
My case should the 2nd case,   git push complete OK,  but the url which is generated to create review is non-finishing after open.   I will check /etc/critic/main/configuration/base.py  :-)

**Comment by fyfcauc** [comment]
Strange, I check the conf, but can not find some issues.....

It is a pleasure if you can check it:

SYSTEM_IDENTITY = "main"
SYSTEM_USER_NAME = "critic"
SYSTEM_USER_EMAIL = "critic@10.44.155.171"
SYSTEM_GROUP_NAME = "critic"
SYSTEM_RECIPIENTS = ['fengyufei <fengyufei@renrenche.com>']
HOSTNAME = "10.44.155.171"
AUTHENTICATION_MODE = "critic"
SESSION_TYPE = "cookie"
SESSION_MAX_AGE = 0
ALLOW_ANONYMOUS_USER = True
ACCESS_SCHEME = "http"
REPOSITORY_URL_TYPES = ['http']
DEFAULT_ENCODINGS = ['utf-8', 'latin-1']
ALLOW_USER_REGISTRATION = True
USER_NAME_PATTERN = r"^\w[-\._\w]*\w$"
USER_NAME_PATTERN_DESCRIPTION = (
    "Must contain only alpha-numerics, periods, underscores or dashes, and "
    "must start and end with alpha-numerics, and be at least two characters "
    "long.")
VERIFY_EMAIL_ADDRESSES = True
ARCHIVE_REVIEW_BRANCHES = True

The generated url is http://10.44.155.171/createreview?repository=1&branch=test5.

**Comment by jensl** [comment]
That looks perfectly reasonable to me. If that URL doesn't work, and http://10.44.155.171/ does, then I don't know what might be wrong.

If the repository has a very long history (many commits) and the branch contains lots of commits that it doesn't have in common with the repository's master branch, then loading the createreview page could take quite a lot of time, since Critic would then analyze all those commits, which can take quite a while in extreme cases.

If you load http://10.44.155.171/branches?repository=1 there should be a line for the branch test5. The third column on that line is the number of commits Critic figures belongs to the branch. That's the same number of commits that would be analyzed when loading the createreview page.

**Comment by fyfcauc** [comment]
thx for your support :-)

**Comment by fyfcauc** [comment]
Update the investigation, the ever-lasting happens in code: critic.py(line:658,  class WrappedResult: **self.first = self.result.next()** is blocking and no-ending). the request method id "showcommit". Looks like **renderShowCommit(req, db, user)** return a generator, while if you want to get next value, it is ever-lasting and blocking.

**Comment by fyfcauc** [comment]
Finally I found the root cause:
In background/utils.py, the class JSONJobServer's __init__:
self.__max_workers = service.get("max_workers", 4)
do not know why, the __max_workers is 0.......
, so __startJobs(self) do nothing,
 just hardcode it as 8, looks like work.

**Comment by jensl** [comment]
(Late respons.)

Many thanks for the analysis of the issue, and sorry about the trouble this caused you. I've landed https://critic-review.org/r/339 which should prevent the installation script to set the max_workers setting to zero initially (when installing on a single-CPU system,) which I guess is what happened for you.

If you look at /etc/critic/main/configuration/services.py, you could change the setting to non-zero manually, and then revert you workaround (if you like.) Setting it to 8 might be a bit overkill, especially if the system really has only one CPU, since the individual jobs can be quite big, and thus not suited to run very many of in parallel.
