### ISSUE TITLE
The upgrade.py script wipes the configured apache ssl certificate setting

### ISSUE THREAD

**Issue by petternilsen** [jensl/critic#99]
/etc/apache2/ssl contains the lines:

SSLEngine on
       SSLCertificateFile /etc/apache2/ssl/critic.viv.int.crt
       SSLCertificateKeyFile /etc/apache2/ssl/critic.viv.int.key

This file is being overwritten by the upgrade.py script. It should not do that obviously.  I've not seen where it does it so I can disable it, though?

**Comment by jensl** [comment]
Makes no sense to me. The installation script doesn't support doing any kind of SSL configuration, and should only write directly to /etc/apache2/sites-available/critic-main, and then use a2ensite to enable that side. It also uses a2dissite (to disable the default site) and a2enmod to enable modules, but I don't see how any of that could do anything with /etc/apache2/ssl.

What is the file being overwritten with?

Also, I would point out that it doesn't really make sense that /etc/apache2/ssl is a file containing references to files under /etc/apache2/ssl/ as if it was also a directory.

**Comment by petternilsen** [comment]
Sorry, that was just obviously not the file, but the _files_ inside the directory. The reference to them in the sites-available directory configuration files for critic are overwritten and those lines are dropped.  Should an update really overwrite existing configuration?

**Comment by jensl** [comment]
Ah, so those lines are from the generated sites-available/critic-main file? Then the behavior makes more sense.

The upgrade script does support upgrading generated configuration files, but it asks for permission first. On critic-review.org I have similar additions to the generated site file, and I've certainly upgraded that system using upgrade.py numerous times without having those additions overwritten (because I always decline when the script offers to update the site file.)

This upgrading logic is unfortunately a bit stupid, so it will effectively always offer to revert all your modifications for you when you upgrade. (I.e., it current can't tell whether the changes it proposes are reverts of your local modifications, or if it's genuine changes in how the file is being generated.)

**Comment by petternilsen** [comment]
Ok, I did it twice, but didn't see the question. I'll keep a look out for it on the next try on our test server.

**Comment by jensl** [comment]
The management of web server configuration files was of course quite recently changed, so it's possibly the question got lost recently.

**Comment by petternilsen** [comment]
I do get asked so I goofed, sorry.
